USER: admin
PASSWORD: 111111
server:
  port: 9527
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://${USER}:${PASSWORD}@eurekaServer01.com:7001/eureka/,http://${USER}:${PASSWORD}@eurekaServer02.com:7002/eureka/,http://${USER}:${PASSWORD}@eurekaServer03.com:7003/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
zuul:
  routes:
    upload:
      path: /upload/**
      serviceId: UPLOAD_SERVICE

