USER: admin
PASSWORD: 111111
server:
  port: 8001
spring:
  application:
    name: upload-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${USER}:${PASSWORD}@eurekaServer01.com:7001/eureka/,http://${USER}:${PASSWORD}@eurekaServer02.com:7002/eureka/,http://${USER}:${PASSWORD}@eurekaServer03.com:7003/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true         #将IP注册到服务注册中心

#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'


